<?php

namespace lib\errors;

define("ERROR_TAPE_DIR_NOT_SPECIFIED", 1); // scan dir
define("ERROR_LOCAL_DIR_NOT_SPECIFIED", 2);
define("ERROR_MHIL_FILES_NOT_SPECIFIED", 3);
define('ERROR_INVALID_ARGUMENTS', 4);
define('ERROR_NO_HASH_FOUND_IN_MHL', 5);
define('ERROR_FILE_NOT_FOUND_ON_STORAGE', 6);
define('ERROR_INVALID_MHL_HASHING_OUTPUT', 7);
define('ERROR_INVALID_MHL_PATH', 8);

define('ERRORS_ALL', [
    ERROR_TAPE_DIR_NOT_SPECIFIED,
    ERROR_LOCAL_DIR_NOT_SPECIFIED,
    ERROR_MHIL_FILES_NOT_SPECIFIED,
    ERROR_INVALID_ARGUMENTS,
    ERROR_NO_HASH_FOUND_IN_MHL,
    ERROR_FILE_NOT_FOUND_ON_STORAGE,
    ERROR_INVALID_MHL_HASHING_OUTPUT,
    ERROR_INVALID_MHL_PATH,
]);

