<?php

define("ERROR_SCAN_DIR_NOT_SPECIFIED", 1);
define('ERROR_INVALID_ARGUMENTS', 2);
define('ERROR_NO_HASH_FOUNT_IN_MHL', 3);
define('ERROR_FILE_NOT_FOUNT_ON_STORAGE', 4);
define('ERROR_INVALID_MHL_HASHING_OUTPUT', 5);

define('ERRORS_ALL', [
    ERROR_SCAN_DIR_NOT_SPECIFIED,
    ERROR_INVALID_ARGUMENTS,
    ERROR_NO_HASH_FOUNT_IN_MHL,
    ERROR_FILE_NOT_FOUNT_ON_STORAGE,
    ERROR_INVALID_MHL_HASHING_OUTPUT,
]);

